repos:
  - repo: git://github.com/MakarovS96/terraform_sf
    rev: v1.0.0
    hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false

    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color

    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false

    - id: terraform_tflint
      args:
        - --args=--deep
        - --args=--enable-rule=terraform_documented_variables