repos:
  - repo: https://github.com/SkillfactoryCoding/DEVOPS-infrastructure-pre-commit-terraform.git
    rev: v1.64.1
    hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false

    - id: terraform_validate

    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false

    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_documented_variables